version: '3.1'
services:
    mysql:
        container_name: iwannaeat-mysql
        platform: linux/x86_64
        image: mysql:5.7
        working_dir: /iwannaeat
        volumes:
            - './app:/iwannaeat'
        environment:
            - MYSQL_ROOT_PASSWORD=iwannaeat
            - MYSQL_DATABASE=iwannaeat
            - MYSQL_USER=iwannaeat
            - MYSQL_PASSWORD=iwannaeat
        ports:
            - '40009:3306'
        networks:
            - iwannaeat-net

    mongodb:
        container_name: iwannaeat-mongodb
        platform: linux/x86_64
        image: 'mongo:4.4.14'
        environment:
            - MONGO_INITDB_DATABASE=iwannaeat
            - MONGO_INITDB_ROOT_USERNAME=iwannaeat
            - MONGO_INITDB_ROOT_PASSWORD=iwannaeat
        ports:
            - "40017:27017"
        networks:
            - iwannaeat-net

    webserver:
        container_name: iwannaeat-webserver
        image: 'nginx:alpine'
        working_dir: /iwannaeat
        volumes:
            - './app:/iwannaeat'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '40007:80'
        networks:
            iwannaeat-net:
                aliases:
                    - api.iwannaeat.local

    php-fpm:
        container_name: iwannaeat-php-fpm
        build: docker/php-fpm
        working_dir: /iwannaeat
        volumes:
            - './app:/iwannaeat'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
        depends_on:
            - webserver
            - mysql
            - mongodb
        links:
            - webserver
            - mysql
            - mongodb
        networks:
            - iwannaeat-net

networks:
    iwannaeat-net:
        driver: bridge
