# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    mongodb_uri: '%env(BROADWAY_READ_MODEL_MONGODB_URI)%'
    mongodb_database: '%env(BROADWAY_READ_MODEL_MONGODB_DATABASE)%'
    api_base_uri: '%env(API_BASE_URI)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    IWannaEat\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
            - '../src/Application/ApiController'

    IWannaEat\Application\ApiController\:
        resource: '../src/Application/ApiController'
        tags: ['controller.service_arguments']



    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    IWannaEat\Infrastructure\EventStoreManager:
        public: true

    iwannaeat.order_recap.read_model.repository:
        class: Broadway\ReadModel\MongoDB\MongoDBRepository
        factory: ['@broadway.read_model.mongodb.repository_factory', create]
        arguments:
            - 'order_recap'
            - 'IWannaEat\Application\Order\OrderRecapModel'

    IWannaEat\Application\Order\OrderAggregateRepository:
        arguments:
            $eventStore: '@broadway.event_store.dbal'
            $eventBus: '@broadway.event_handling.event_bus'
            $aggregateFactory: '@broadway.event_sourcing.aggregate_factory.public'
            $aggregateClass: '_hardcoded_'

    IWannaEat\Application\Order\OrderHandler:
        tags: [broadway.command_handler]

    IWannaEat\Application\Order\OrderRecapProjector:
        arguments:
            $repository: '@iwannaeat.order_recap.read_model.repository'
        tags: [broadway.domain.event_listener]
